name: game_poo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  custom_accordion: ^1.0.0
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  localstorage: ^4.0.1+4
  rflutter_alert: ^2.0.7
  rounded_loading_button: ^2.1.0
  simple_animated_button: ^0.0.9
  simple_animation_progress_bar: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Space
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
